### PR TITLE
Add initial comment support [resurrected]

### PR DESCRIPTION
**Pull request by sungam3r**
This is a duplicate of #16 with resolved test issues

### CODE REVIEW

**Comment by joemcbride** [comment]
Would you mind making the `\r\n` thing cross-platform?  Use `Environment.NewLine`.  That way these tests can still be ran on macOS.  (I do most of my dev on macOS)

**Comment by sungam3r** [comment]
Thanks!

Now, as I understand it, I need a new version of this library to use it in GraphQL package to bring comment support?

 Also, will you have time to look at #23 and #24 ?

**Comment by joemcbride** [comment]
Yes will need a new version.  I can get those other PRs merged and publish a new nuget.

**Comment by sungam3r** [comment]
Probably first it will be a prerelease nuget (for checking any unforeseen errors) which I can use in prerelease GraphQL or immediately release version? I do not really understand a good release strategy for dependent stacks of libraries.

**Comment by joemcbride** [comment]
@sungam3r  I pushed `3.1.0-preview-39` of `GraphQL-Parser` to nuget.

**Pull request merged**
