### PR TITLE
Verify CI tests

### PR DESCRIPTION
**Pull request by Shane32**
Verify CI checks work across forks.  The CI tests should fail.  Do not merge.

### CODE REVIEW

**Comment by Shane32** [comment]
Both changes should fail CI checks.  Something's not working correctly with the CI check setup @sungam3r

**Comment by Shane32** [comment]
Also see my notes in #75 - one of the 4 tests passed when it should not have.

**Comment by sungam3r** [comment]
@Shane32  Can be closed after we have moved to GitHub Actions?

**Comment by Shane32** [comment]
Yes, the prior problem was with appveyor, not the tests.  We should be able to close this now.

**Pull request closed without merging**
