### PR TITLE
Convert solution to file-scoped namespaces

### PR DESCRIPTION
**Pull request by sungam3r**
Thanks to .editorconfig: https://stackoverflow.com/questions/69889519/vs-2022-convert-to-file-scoped-namespace-in-all-files

### CODE REVIEW

**Comment by sungam3r** [comment]
@Shane32 I'll merge this ASAP, I changed only namespaces, no other changes.

**Comment by sungam3r** [comment]
It seems that CodeQL doesn't understand file-scoped namespaces https://github.com/github/codeql/issues/7544

**Comment by Shane32** [comment]
So … does that mean this PR needs to be reverted?

**Comment by sungam3r** [comment]
No. CodeQL workflow works and green. Waiting for answer from CodeQL team. At least now we know about sucj issue 👍 .

**Pull request merged**
