### PR TITLE
Fix NRE when printing directive without locations

### PR DESCRIPTION
**Pull request by sungam3r**
Edge case in tests for https://github.com/sungam3r/graphql-introspection-model

### CODE REVIEW

**Review by Shane32 — APPROVED** [review]
The real problem is that we have `= null!;` as the property initializer, which we should not if we are exposing the class publicly.

**Comment by sungam3r** [comment]
I can argue. `= null!` is done by following the GraphQL grammar - the AST node for locations is not optional. For optional nodes we do have `?` in their property type.

**Comment by sungam3r** [comment]
I mean any property in AST node may be uninialized now if constructed manually. Parser throws exception if locations not set into parsed text.

**Comment by Shane32** [comment]
Right but what I mean is that we should have a constructor which requires a value and remove the default constructor, in order for the NRT attributes to be accurate always. Then “= null!” is not required. Or, make the default constructors internal.

Certainly the NRT attributes are correct as-is to match the AST parsing.

**Comment by Shane32** [comment]
Internally we can still do it the other way.  But the `public` constructor would have proper NRT attributes.  We can also allow for users to pass in `null!` if they like to the constructor, but they are then knowingly breaking NRT semantics.

**Comment by sungam3r** [comment]
Understood.

**Pull request merged**
