### PR TITLE
Add properties to exception

### PR DESCRIPTION
**Pull request by Shane32**
This PR adds 3 new properties to the `GraphQLSyntaxErrorException` class:
* Description
* Line
* Column

The `Message` property will not change.  All tests that verify the `Message` property have been updated to verify the values in these new fields.

### CODE REVIEW

**Comment by Shane32** [comment]
See https://github.com/graphql-dotnet/graphql-dotnet/pull/1765

These added properties will allow graphql-dotnet to return location information from the parser back to the response graph.

**Comment by sungam3r** [comment]
Thanks. You should also bump minor version.

**Comment by sungam3r** [comment]
See https://github.com/graphql-dotnet/parser/pull/67/files

**Comment by Shane32** [comment]
Sorry about that.  I've not published any nuget packages myself yet, so not used to versioning.  Our internal projects just use a date code.

**Pull request merged**
