### PR TITLE
Use AsTask()

### PR DESCRIPTION
**Pull request by sungam3r**
See notes in #332.

### CODE REVIEW

**Comment by sungam3r** [comment]
CA2012 nowarn still exists for tests

**Comment by Shane32** [comment]
I did not use AsTask so as to be sure that there was no allocation occurring. But whatever you think.

**Review by Shane32 — APPROVED** [review]

**Comment by sungam3r** [comment]
изображение

**Comment by Shane32** [comment]
Excellent!

**Pull request merged**
