### PR TITLE
Bump PublicApiGenerator from 10.3.0 to 11.0.0

### PR DESCRIPTION
**Pull request by sungam3r**

### CODE REVIEW

**Comment by Shane32** [comment]
This reveals that we have obvious flaws in our public API surface, as we have `init;` properties with no other way to set the property.

**Comment by sungam3r** [comment]
> init; properties with no other way to set the property.

But... this is the purpose of init.

**Comment by Shane32** [comment]
`init;` is not compatible with certain runtimes, namely, .NET Framework.  A constructor is necessary if we want to maintain compatibility with .NET Framework.

**Comment by Shane32** [comment]
See:
- https://github.com/graphql-dotnet/graphql-dotnet/issues/3322

**Comment by sungam3r** [comment]
I remember that issue with ValidationOptions.

**Comment by sungam3r** [comment]
> if we want to maintain compatibility with .NET Framework.

Yep but nobody complained.

**Pull request merged**
