### PR TITLE
Tune CI

### LINKED ISSUE #167: Something wrong with CodeCov
1. Deal with `<Include>[GraphQL-Parser]*</Include>`.
2. Why some PRs have no code coverage comment (#166) but other (#168) has.

### PR DESCRIPTION
**Pull request by sungam3r**
fixes #167 and #231

### CODE REVIEW

**Comment by Shane32** [comment]
So you're removing the debug.assert for all CI runs?

**Comment by sungam3r** [comment]
Yes, only from CI runs but keep for local runs. I believe that eventually https://github.com/coverlet-coverage/coverlet/issues/258 will be fixed.

**Comment by Shane32** [comment]
Well, ok

> I believe that eventually [coverlet-coverage/coverlet#258](https://github.com/coverlet-coverage/coverlet/issues/258) will be fixed.

I would find that quite unlikely, but anything's possible.

**Comment by sungam3r** [comment]
Strange, but another `Debug.Assert()` here https://app.codecov.io/gh/graphql-dotnet/parser/blob/master/src/GraphQLParser/ParserContext.Parse.cs is covered 😕 .

**Review by Shane32 — APPROVED** [review]

**Comment by Shane32** [comment]
This is all great, but you should not expect all contributors to maintain 100.00% code coverage in this repo.

**Comment by sungam3r** [comment]
Wait, I understand now that this is not an issue with `Debug.Assert` at all. The issue is `&&` operator inside it.

**Comment by sungam3r** [comment]
> This is all great, but you should not expect all contributors to maintain 100.00% code coverage in this repo.

 all contributors = 2 people 😞

**Comment by Shane32** [comment]
Well, yeah, we can hope for more....

**Comment by sungam3r** [comment]
Yep.

**Comment by sungam3r** [comment]
CodeQL dislikes & 😄 
изображение

**Comment by sungam3r** [comment]
100%
изображение

**Pull request merged**
